"""Literal terminal overrides, owned output files, and read-only font discovery."""
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from .envfile import PreferenceError
from .model import validate_value

KEYS = ('readability.font_family', 'readability.ghostty_font_size',
        'readability.kitty_font_size', 'readability.background_opacity')
MARKER = b'# dotfiles managed readability v1\n'
HEADER = MARKER + b'# Generated by personalize.sh; set or reset readability.* preferences to change.\n'
OUTPUT_NAMES = ('ghostty.conf', 'kitty.conf')


def output_paths(preferences):
    """The only readability files a personalization transaction may own."""
    return tuple(preferences.directory/'readability'/name for name in OUTPUT_NAMES)


def validate_owned(path, previous):
    """Accept absent or explicitly owned regular files; never adopt personal files."""
    path = Path(path)
    if path.is_symlink() or path.parent.is_symlink():
        raise PreferenceError('Refusing a readability symlink; inspect ownership: ' + str(path))
    if previous is not None and not previous.startswith(MARKER):
        raise PreferenceError('Readability file is not managed by dotfiles; preserve it before applying: ' + str(path))


def render_files(preferences, values):
    """Return bytes only. Null/reset removes directives and retains a harmless header."""
    for key in KEYS:
        validate_value(key, values.get(key), preferences.repo, preferences.home)
    ghostty, kitty = [], []
    family = values.get('readability.font_family')
    if family is not None:
        # Ghostty font-family is a repeatable fallback list. Reset its inherited
        # entries before the preferred family, otherwise the base font stays first.
        ghostty += ['font-family =', 'font-family = ' + family]
        # Kitty parses apostrophes as font-spec syntax. An explicit family field
        # with a quoted literal preserves the exact name, including apostrophes.
        kitty.append('font_family family=' + json.dumps(family, ensure_ascii=False))
    for name, lines, option in [('ghostty', ghostty, 'font-size = '), ('kitty', kitty, 'font_size ')]:
        size = values.get('readability.' + name + '_font_size')
        if size is not None:
            lines.append(option + format(size, '.12g'))
    opacity = values.get('readability.background_opacity')
    if opacity is not None:
        ghostty.append('background-opacity = ' + format(opacity, '.12g'))
        kitty.append('background_opacity ' + format(opacity, '.12g'))
    return {path: HEADER + (('\n'.join(lines) + '\n').encode() if lines else b'')
            for path, lines in zip(output_paths(preferences), (ghostty, kitty))}


def families_from_profiler(data):
    """Only enabled, valid macOS font faces count as installed families."""
    if not isinstance(data, dict) or not isinstance(data.get('SPFontsDataType'), list):
        raise PreferenceError('Font discovery returned malformed macOS metadata')
    families = set()
    for item in data['SPFontsDataType']:
        if not isinstance(item, dict) or item.get('enabled') == 'no' or item.get('valid') == 'no':
            continue
        faces = item.get('typefaces', [])
        if not isinstance(faces, list):
            continue
        for face in faces:
            if not isinstance(face, dict) or face.get('enabled') == 'no' or face.get('valid') == 'no':
                continue
            family = face.get('family')
            if isinstance(family, str) and family and family.isprintable():
                families.add(family)
    return sorted(families, key=str.casefold)


def discover_fonts():
    """Explicit local metadata query; never launch a terminal or install fonts."""
    if sys.platform == 'darwin':
        command = ['/usr/sbin/system_profiler', 'SPFontsDataType', '-json']
    else:
        binary = shutil.which('fc-list')
        if not binary:
            raise PreferenceError('Font discovery unavailable: fc-list is not installed')
        command = [binary, '--format=%{family}\n']
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=20,
                                env=dict(os.environ, LC_ALL='C', PYTHONUTF8='1'))
    except (OSError, subprocess.TimeoutExpired):
        raise PreferenceError('Font discovery unavailable; existing preferences were not changed') from None
    if result.returncode:
        raise PreferenceError('Font discovery failed; existing preferences were not changed')
    try:
        families = families_from_profiler(json.loads(result.stdout)) if sys.platform == 'darwin' else sorted(
            {family.strip() for line in result.stdout.splitlines() for family in line.split(',') if family.strip()},
            key=str.casefold)
    except (ValueError, TypeError):
        raise PreferenceError('Font discovery returned invalid metadata') from None
    if not families:
        raise PreferenceError('Font discovery found no enabled families; existing preferences were not changed')
    return families


def require_font(values, families):
    """Validate against an explicit discovery snapshot; this function has no effects."""
    family = values.get('readability.font_family')
    if family is not None and family.casefold() not in {name.casefold() for name in families}:
        raise PreferenceError('Font family is not installed: ' + family + '. Use list-fonts before applying.')
